//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VotingCoreWeb.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AccountRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AccountRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VotingCoreWeb.Properties.AccountRes", typeof(AccountRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Změnit e-mail.
        /// </summary>
        public static string BUTTON_CHANGE_EMAIL {
            get {
                return ResourceManager.GetString("BUTTON_CHANGE_EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Změnit heslo.
        /// </summary>
        public static string BUTTON_CHANGE_PASSWORD {
            get {
                return ResourceManager.GetString("BUTTON_CHANGE_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zadat heslo.
        /// </summary>
        public static string BUTTON_CREATE_PASSWORD {
            get {
                return ResourceManager.GetString("BUTTON_CREATE_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smazat data a odstranit účet.
        /// </summary>
        public static string BUTTON_DELETE_ACCOUNT {
            get {
                return ResourceManager.GetString("BUTTON_DELETE_ACCOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zapomenuté heslo?.
        /// </summary>
        public static string BUTTON_FORGOTTEN_PASSWORD {
            get {
                return ResourceManager.GetString("BUTTON_FORGOTTEN_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Přihlásit se.
        /// </summary>
        public static string BUTTON_LOGIN {
            get {
                return ResourceManager.GetString("BUTTON_LOGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smazat.
        /// </summary>
        public static string BUTTON_PERSONAL_DATA_DELETE {
            get {
                return ResourceManager.GetString("BUTTON_PERSONAL_DATA_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stáhnout.
        /// </summary>
        public static string BUTTON_PERSONAL_DATA_DOWNLOAD {
            get {
                return ResourceManager.GetString("BUTTON_PERSONAL_DATA_DOWNLOAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uložit.
        /// </summary>
        public static string BUTTON_PROFILE_SAVE {
            get {
                return ResourceManager.GetString("BUTTON_PROFILE_SAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nastavit heslo.
        /// </summary>
        public static string BUTTON_RESET {
            get {
                return ResourceManager.GetString("BUTTON_RESET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to klikněte sem pro přihlášení.
        /// </summary>
        public static string BUTTON_RESET_LOGIN {
            get {
                return ResourceManager.GetString("BUTTON_RESET_LOGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odeslat e-mail s instrukcemi.
        /// </summary>
        public static string BUTTON_SEND_EMAIL {
            get {
                return ResourceManager.GetString("BUTTON_SEND_EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vyplňte formulář a změňte své heslo.
        /// </summary>
        public static string CHANGE_HEADER {
            get {
                return ResourceManager.GetString("CHANGE_HEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potvrzení nového hesla.
        /// </summary>
        public static string CHANGE_PASSWORD_CONFIRM {
            get {
                return ResourceManager.GetString("CHANGE_PASSWORD_CONFIRM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nové heslo.
        /// </summary>
        public static string CHANGE_PASSWORD_NEW {
            get {
                return ResourceManager.GetString("CHANGE_PASSWORD_NEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Současné heslo.
        /// </summary>
        public static string CHANGE_PASSWORD_OLD {
            get {
                return ResourceManager.GetString("CHANGE_PASSWORD_OLD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Změna hesla.
        /// </summary>
        public static string CHANGE_TITLE {
            get {
                return ResourceManager.GetString("CHANGE_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potvrzení změny e-mailu.
        /// </summary>
        public static string CONFIRM_EMAIL_TITLE {
            get {
                return ResourceManager.GetString("CONFIRM_EMAIL_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heslo.
        /// </summary>
        public static string DELETE_ACCOUNT_PASSWORD {
            get {
                return ResourceManager.GetString("DELETE_ACCOUNT_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zadané heslo nesouhlasí..
        /// </summary>
        public static string DELETE_ACCOUNT_PASSWORD_INVALID {
            get {
                return ResourceManager.GetString("DELETE_ACCOUNT_PASSWORD_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smazání osobních údajů.
        /// </summary>
        public static string DELETE_ACCOUNT_TITLE {
            get {
                return ResourceManager.GetString("DELETE_ACCOUNT_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smazáním těchto dat dojde k trvalému odstranění vašeho účtu. Jde o nevratnou změnu..
        /// </summary>
        public static string DELETE_ACCOUNT_WARNING {
            get {
                return ResourceManager.GetString("DELETE_ACCOUNT_WARNING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prosím, potvrďte svůj účet na portálu hlasovali.eu kliknutím &lt;a href=&quot;{0}&quot;&gt;sem&lt;/a&gt;..
        /// </summary>
        public static string EMAIL_CONFIRM_BODY {
            get {
                return ResourceManager.GetString("EMAIL_CONFIRM_BODY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potvrďte svůj účet.
        /// </summary>
        public static string EMAIL_CONFIRM_SUBJECT {
            get {
                return ResourceManager.GetString("EMAIL_CONFIRM_SUBJECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pokud jste požádal/a o přenastavení hesla na portálu hlasovali.eu, přejděte &lt;a href=&quot;{0}&quot;&gt;sem&lt;/a&gt;..
        /// </summary>
        public static string EMAIL_RESET_BODY {
            get {
                return ResourceManager.GetString("EMAIL_RESET_BODY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zapomenuté heslo.
        /// </summary>
        public static string EMAIL_RESET_SUBJECT {
            get {
                return ResourceManager.GetString("EMAIL_RESET_SUBJECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mailová adresa.
        /// </summary>
        public static string FORGOT_EMAIL {
            get {
                return ResourceManager.GetString("FORGOT_EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zadejte vaši e-mailovou adresu, na kterou vám zašleme instrukce k přenastavení hesla..
        /// </summary>
        public static string FORGOT_HEADER {
            get {
                return ResourceManager.GetString("FORGOT_HEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prosím zkontrolujte svoji e-mailovou schránku. Dorazí vám e-mail s instrukcemi k přenastavení hesla..
        /// </summary>
        public static string FORGOT_SENT_HEADER {
            get {
                return ResourceManager.GetString("FORGOT_SENT_HEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email odeslán.
        /// </summary>
        public static string FORGOT_SENT_TITLE {
            get {
                return ResourceManager.GetString("FORGOT_SENT_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zapomenuté heslo.
        /// </summary>
        public static string FORGOT_TITLE {
            get {
                return ResourceManager.GetString("FORGOT_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mailová adresa.
        /// </summary>
        public static string LOGIN_EMAIL {
            get {
                return ResourceManager.GetString("LOGIN_EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neplatný e-mail nebo heslo.
        /// </summary>
        public static string LOGIN_FAILED {
            get {
                return ResourceManager.GetString("LOGIN_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Přihlašte se pomocí svého e-mailu a hesla.
        /// </summary>
        public static string LOGIN_HEADER {
            get {
                return ResourceManager.GetString("LOGIN_HEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neplatné přihlašovací údaje.
        /// </summary>
        public static string LOGIN_INVALID_ATTEMPT {
            get {
                return ResourceManager.GetString("LOGIN_INVALID_ATTEMPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heslo.
        /// </summary>
        public static string LOGIN_PASSWORD {
            get {
                return ResourceManager.GetString("LOGIN_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zaregistrovat se jako nový uživatel.
        /// </summary>
        public static string LOGIN_REGISTER {
            get {
                return ResourceManager.GetString("LOGIN_REGISTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zapamatovat si mě.
        /// </summary>
        public static string LOGIN_REMEMBER_ME {
            get {
                return ResourceManager.GetString("LOGIN_REMEMBER_ME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Přihlášení.
        /// </summary>
        public static string LOGIN_TITLE {
            get {
                return ResourceManager.GetString("LOGIN_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Úspěšně jste se odhlásil/a..
        /// </summary>
        public static string LOGOUT_HEADER {
            get {
                return ResourceManager.GetString("LOGOUT_HEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odhlášení.
        /// </summary>
        public static string LOGOUT_TITLE {
            get {
                return ResourceManager.GetString("LOGOUT_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stávající e-mail.
        /// </summary>
        public static string MANAGE_EMAIL_CURRENT_EMAIL {
            get {
                return ResourceManager.GetString("MANAGE_EMAIL_CURRENT_EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nový e-mail.
        /// </summary>
        public static string MANAGE_EMAIL_NEW_EMAIL {
            get {
                return ResourceManager.GetString("MANAGE_EMAIL_NEW_EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Změna e-mailu.
        /// </summary>
        public static string MANAGE_EMAIL_TITLE {
            get {
                return ResourceManager.GetString("MANAGE_EMAIL_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uživatelské jméno.
        /// </summary>
        public static string MANAGE_EMAIL_USERNAME {
            get {
                return ResourceManager.GetString("MANAGE_EMAIL_USERNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Změňte nastavení svého účtu.
        /// </summary>
        public static string MANAGE_HEADER {
            get {
                return ResourceManager.GetString("MANAGE_HEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nastavení účtu.
        /// </summary>
        public static string MANAGE_TITLE {
            get {
                return ResourceManager.GetString("MANAGE_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail.
        /// </summary>
        public static string MENU_EMAIL {
            get {
                return ResourceManager.GetString("MENU_EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heslo.
        /// </summary>
        public static string MENU_PASSWORD {
            get {
                return ResourceManager.GetString("MENU_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Osobní údaje.
        /// </summary>
        public static string MENU_PERSONAL_DATA {
            get {
                return ResourceManager.GetString("MENU_PERSONAL_DATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Účet.
        /// </summary>
        public static string MENU_PROFILE {
            get {
                return ResourceManager.GetString("MENU_PROFILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Změna e-mailu byla úspěšně dokončena..
        /// </summary>
        public static string MESSAGE_CHANGE_EMAIL_SUCCESS {
            get {
                return ResourceManager.GetString("MESSAGE_CHANGE_EMAIL_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Při změně e-mailu došlo k chybě.
        /// </summary>
        public static string MESSAGE_EMAIL_CHANGE_ERROR {
            get {
                return ResourceManager.GetString("MESSAGE_EMAIL_CHANGE_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vaší novou schránku potvrdíte prokliknutím z emailu, který Vám byl zaslán..
        /// </summary>
        public static string MESSAGE_EMAIL_SENT {
            get {
                return ResourceManager.GetString("MESSAGE_EMAIL_SENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vaše heslo bylo změněno.
        /// </summary>
        public static string MESSAGE_PASSWORD_CHANGED {
            get {
                return ResourceManager.GetString("MESSAGE_PASSWORD_CHANGED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vaše heslo bylo nastaveno.
        /// </summary>
        public static string MESSAGE_PASSWORD_SET {
            get {
                return ResourceManager.GetString("MESSAGE_PASSWORD_SET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Váš účet byl aktualizován.
        /// </summary>
        public static string MESSAGE_PROFILE_SAVED {
            get {
                return ResourceManager.GetString("MESSAGE_PROFILE_SAVED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Při změně uživatelského jména došlo k chybě.
        /// </summary>
        public static string MESSAGE_USERNAME_CHANGE_ERROR {
            get {
                return ResourceManager.GetString("MESSAGE_USERNAME_CHANGE_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Váš účet obsahuje osobní údaje, které jste nám předal. Tato stránka umožňuje data stáhnout nebo smazat..
        /// </summary>
        public static string PERSONAL_DATA_HEADER {
            get {
                return ResourceManager.GetString("PERSONAL_DATA_HEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Osobní údaje.
        /// </summary>
        public static string PERSONAL_DATA_TITLE {
            get {
                return ResourceManager.GetString("PERSONAL_DATA_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smazáním těchto dat dojde k trvalému odstranění vašeho účtu. Jde o nevratnou změnu..
        /// </summary>
        public static string PERSONAL_DATA_WARNING {
            get {
                return ResourceManager.GetString("PERSONAL_DATA_WARNING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefonní číslo.
        /// </summary>
        public static string PROFILE_PHONE_NUMBER {
            get {
                return ResourceManager.GetString("PROFILE_PHONE_NUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Účet.
        /// </summary>
        public static string PROFILE_TITLE {
            get {
                return ResourceManager.GetString("PROFILE_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uživatelské jméno.
        /// </summary>
        public static string PROFILE_USERNAME {
            get {
                return ResourceManager.GetString("PROFILE_USERNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vaše heslo bylo přenastaveno. Prosím.
        /// </summary>
        public static string RESET_DONE {
            get {
                return ResourceManager.GetString("RESET_DONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mailová adresa.
        /// </summary>
        public static string RESET_EMAIL {
            get {
                return ResourceManager.GetString("RESET_EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vyplněním následujících polí přenastavíte své heslo.
        /// </summary>
        public static string RESET_HEADER {
            get {
                return ResourceManager.GetString("RESET_HEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nové heslo.
        /// </summary>
        public static string RESET_PASSWORD {
            get {
                return ResourceManager.GetString("RESET_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potvrďte nové heslo.
        /// </summary>
        public static string RESET_PASSWORD_CONFIRM {
            get {
                return ResourceManager.GetString("RESET_PASSWORD_CONFIRM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Přenastavit heslo.
        /// </summary>
        public static string RESET_TITLE {
            get {
                return ResourceManager.GetString("RESET_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heslo a jeho potvrzení neodpovídají.
        /// </summary>
        public static string VALIDATION_PASSWORD_CONFIRM {
            get {
                return ResourceManager.GetString("VALIDATION_PASSWORD_CONFIRM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heslo musí být alespoň {2} znaků dlouhé.
        /// </summary>
        public static string VALIDATION_PASSWORD_LENGTH {
            get {
                return ResourceManager.GetString("VALIDATION_PASSWORD_LENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pole e-mail musí být vyplněno.
        /// </summary>
        public static string VALIDATION_REQUIRED_EMAIL {
            get {
                return ResourceManager.GetString("VALIDATION_REQUIRED_EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pole heslo musí být vyplněno.
        /// </summary>
        public static string VALIDATION_REQUIRED_PASSWORD {
            get {
                return ResourceManager.GetString("VALIDATION_REQUIRED_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nové heslo musí být vyplněno.
        /// </summary>
        public static string VALIDATION_REQUIRED_PASSWORD_NEW {
            get {
                return ResourceManager.GetString("VALIDATION_REQUIRED_PASSWORD_NEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Současné heslo musí být vyplněno.
        /// </summary>
        public static string VALIDATION_REQUIRED_PASSWORD_OLD {
            get {
                return ResourceManager.GetString("VALIDATION_REQUIRED_PASSWORD_OLD", resourceCulture);
            }
        }
    }
}
