//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VotingCoreWeb.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CommonRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CommonRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VotingCoreWeb.Properties.CommonRes", typeof(CommonRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chyba.
        /// </summary>
        public static string ALERT_DANGER {
            get {
                return ResourceManager.GetString("ALERT_DANGER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upozornění.
        /// </summary>
        public static string ALERT_INFO {
            get {
                return ResourceManager.GetString("ALERT_INFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Úspěch.
        /// </summary>
        public static string ALERT_SUCCESS {
            get {
                return ResourceManager.GetString("ALERT_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Varování.
        /// </summary>
        public static string ALERT_WARNING {
            get {
                return ResourceManager.GetString("ALERT_WARNING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hlasování zastupitelstva.
        /// </summary>
        public static string APPLICATION_NAME {
            get {
                return ResourceManager.GetString("APPLICATION_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Akce.
        /// </summary>
        public static string COLUMN_ACTION {
            get {
                return ResourceManager.GetString("COLUMN_ACTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BitEST.
        /// </summary>
        public static string IMPORTER_BITEST {
            get {
                return ResourceManager.GetString("IMPORTER_BITEST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrace.
        /// </summary>
        public static string MENU_ITEM_ADMIN {
            get {
                return ResourceManager.GetString("MENU_ITEM_ADMIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Správa zastupitelů.
        /// </summary>
        public static string MENU_ITEM_ADMIN_DEPUTY {
            get {
                return ResourceManager.GetString("MENU_ITEM_ADMIN_DEPUTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import ze souboru.
        /// </summary>
        public static string MENU_ITEM_ADMIN_IMPORT {
            get {
                return ResourceManager.GetString("MENU_ITEM_ADMIN_IMPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Správa obcí.
        /// </summary>
        public static string MENU_ITEM_ADMIN_MUNICIPALITY {
            get {
                return ResourceManager.GetString("MENU_ITEM_ADMIN_MUNICIPALITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Správa klubů.
        /// </summary>
        public static string MENU_ITEM_ADMIN_PARTY {
            get {
                return ResourceManager.GetString("MENU_ITEM_ADMIN_PARTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zasedání zastupitelstva.
        /// </summary>
        public static string MENU_ITEM_ADMIN_SESSIONS {
            get {
                return ResourceManager.GetString("MENU_ITEM_ADMIN_SESSIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Body jednání.
        /// </summary>
        public static string MENU_ITEM_ADMIN_TOPICS {
            get {
                return ResourceManager.GetString("MENU_ITEM_ADMIN_TOPICS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Správa účtů.
        /// </summary>
        public static string MENU_ITEM_ADMIN_USER {
            get {
                return ResourceManager.GetString("MENU_ITEM_ADMIN_USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hlasování.
        /// </summary>
        public static string MENU_ITEM_ADMIN_VOTINGS {
            get {
                return ResourceManager.GetString("MENU_ITEM_ADMIN_VOTINGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seznam obcí.
        /// </summary>
        public static string MENU_ITEM_HOME {
            get {
                return ResourceManager.GetString("MENU_ITEM_HOME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Přihlásit se.
        /// </summary>
        public static string MENU_ITEM_LOGIN {
            get {
                return ResourceManager.GetString("MENU_ITEM_LOGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odhlásit se.
        /// </summary>
        public static string MENU_ITEM_LOGOUT {
            get {
                return ResourceManager.GetString("MENU_ITEM_LOGOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Správa účtu.
        /// </summary>
        public static string MENU_ITEM_USER {
            get {
                return ResourceManager.GetString("MENU_ITEM_USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ne.
        /// </summary>
        public static string TABLE_VALUE_FALSE {
            get {
                return ResourceManager.GetString("TABLE_VALUE_FALSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ano.
        /// </summary>
        public static string TABLE_VALUE_TRUE {
            get {
                return ResourceManager.GetString("TABLE_VALUE_TRUE", resourceCulture);
            }
        }
    }
}
