//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VotingCoreWeb.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TopicAdminRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TopicAdminRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VotingCoreWeb.Properties.TopicAdminRes", typeof(TopicAdminRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nový bod.
        /// </summary>
        public static string BUTTON_CREATE {
            get {
                return ResourceManager.GetString("BUTTON_CREATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hlasování.
        /// </summary>
        public static string BUTTON_VOTING {
            get {
                return ResourceManager.GetString("BUTTON_VOTING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Procedurální.
        /// </summary>
        public static string COLUMN_IS_PROCEDURAL {
            get {
                return ResourceManager.GetString("COLUMN_IS_PROCEDURAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tajné.
        /// </summary>
        public static string COLUMN_IS_SECRET {
            get {
                return ResourceManager.GetString("COLUMN_IS_SECRET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Název.
        /// </summary>
        public static string COLUMN_NAME {
            get {
                return ResourceManager.GetString("COLUMN_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #.
        /// </summary>
        public static string COLUMN_ORDER {
            get {
                return ResourceManager.GetString("COLUMN_ORDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hlasování.
        /// </summary>
        public static string LABEL_VOTING {
            get {
                return ResourceManager.GetString("LABEL_VOTING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seznam bodů.
        /// </summary>
        public static string PAGE_TITLE {
            get {
                return ResourceManager.GetString("PAGE_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nový bod jednání.
        /// </summary>
        public static string PAGE_TITLE_CREATE {
            get {
                return ResourceManager.GetString("PAGE_TITLE_CREATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odstranit bod jednání.
        /// </summary>
        public static string PAGE_TITLE_DELETE {
            get {
                return ResourceManager.GetString("PAGE_TITLE_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upravit bod jednání.
        /// </summary>
        public static string PAGE_TITLE_UPDATE {
            get {
                return ResourceManager.GetString("PAGE_TITLE_UPDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Body jednání.
        /// </summary>
        public static string TABLE_TITLE {
            get {
                return ResourceManager.GetString("TABLE_TITLE", resourceCulture);
            }
        }
    }
}
