//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VotingWeb.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ImportAdminRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ImportAdminRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VotingWeb.Properties.ImportAdminRes", typeof(ImportAdminRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import ze souboru selhal.
        /// </summary>
        public static string ALERT_IMPORT_FAILED {
            get {
                return ResourceManager.GetString("ALERT_IMPORT_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import ze souboru byl úspěšně proveden.
        /// </summary>
        public static string ALERT_IMPORT_SUCCESS {
            get {
                return ResourceManager.GetString("ALERT_IMPORT_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importovat.
        /// </summary>
        public static string BUTTON_IMPORT {
            get {
                return ResourceManager.GetString("BUTTON_IMPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Načíst.
        /// </summary>
        public static string BUTTON_LOAD {
            get {
                return ResourceManager.GetString("BUTTON_LOAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Předsedající:.
        /// </summary>
        public static string DETAIL_CHAIRMAN {
            get {
                return ResourceManager.GetString("DETAIL_CHAIRMAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Konec jednání:.
        /// </summary>
        public static string DETAIL_DATE_END {
            get {
                return ResourceManager.GetString("DETAIL_DATE_END", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Začátek jednání:.
        /// </summary>
        public static string DETAIL_DATE_START {
            get {
                return ResourceManager.GetString("DETAIL_DATE_START", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Název:.
        /// </summary>
        public static string DETAIL_TITLE {
            get {
                return ResourceManager.GetString("DETAIL_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Název.
        /// </summary>
        public static string DETAIL_TOPIC_NAME {
            get {
                return ResourceManager.GetString("DETAIL_TOPIC_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pořadí hlasování:.
        /// </summary>
        public static string DETAIL_TOPIC_ORDER {
            get {
                return ResourceManager.GetString("DETAIL_TOPIC_ORDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Čas hlasování.
        /// </summary>
        public static string DETAIL_TOPIC_TIME {
            get {
                return ResourceManager.GetString("DETAIL_TOPIC_TIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Není k dispozici.
        /// </summary>
        public static string LABEL_NO_DATE {
            get {
                return ResourceManager.GetString("LABEL_NO_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import ze souboru.
        /// </summary>
        public static string PAGE_TITLE {
            get {
                return ResourceManager.GetString("PAGE_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Načtená data.
        /// </summary>
        public static string PAGE_TITLE_DETAIL {
            get {
                return ResourceManager.GetString("PAGE_TITLE_DETAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import ze souboru.
        /// </summary>
        public static string PAGE_TITLE_FILE {
            get {
                return ResourceManager.GetString("PAGE_TITLE_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Načítání souboru selhalo - {0}.
        /// </summary>
        public static string VALIDATION_FILE_INVALID_FORMAT {
            get {
                return ResourceManager.GetString("VALIDATION_FILE_INVALID_FORMAT", resourceCulture);
            }
        }
    }
}
