//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VotingWeb.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UserAdminRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UserAdminRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VotingWeb.Properties.UserAdminRes", typeof(UserAdminRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nový účet.
        /// </summary>
        public static string BUTTON_CREATE {
            get {
                return ResourceManager.GetString("BUTTON_CREATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spravované obce.
        /// </summary>
        public static string COLUMN_MUNICIPALITIES {
            get {
                return ResourceManager.GetString("COLUMN_MUNICIPALITIES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        public static string COLUMN_ROLES {
            get {
                return ResourceManager.GetString("COLUMN_ROLES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uživatelské jméno.
        /// </summary>
        public static string COLUMN_USER_NAME {
            get {
                return ResourceManager.GetString("COLUMN_USER_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spravovaná obec.
        /// </summary>
        public static string DETAIL_MUNICIPALITY {
            get {
                return ResourceManager.GetString("DETAIL_MUNICIPALITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heslo.
        /// </summary>
        public static string DETAIL_PASSWORD {
            get {
                return ResourceManager.GetString("DETAIL_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        public static string DETAIL_ROLE {
            get {
                return ResourceManager.GetString("DETAIL_ROLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uživatelské jméno.
        /// </summary>
        public static string DETAIL_USER_NAME {
            get {
                return ResourceManager.GetString("DETAIL_USER_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uživatelské účty.
        /// </summary>
        public static string PAGE_TITLE {
            get {
                return ResourceManager.GetString("PAGE_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Založit nový účet.
        /// </summary>
        public static string PAGE_TITLE_CREATE {
            get {
                return ResourceManager.GetString("PAGE_TITLE_CREATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odstranit účet.
        /// </summary>
        public static string PAGE_TITLE_DELETE {
            get {
                return ResourceManager.GetString("PAGE_TITLE_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upravit účet.
        /// </summary>
        public static string PAGE_TITLE_UPDATE {
            get {
                return ResourceManager.GetString("PAGE_TITLE_UPDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uživatelské účty.
        /// </summary>
        public static string TABLE_TITLE {
            get {
                return ResourceManager.GetString("TABLE_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heslo musí být alespoň {2} znaků dlouhé.
        /// </summary>
        public static string VALIDATION_PASSWORD_LENGTH {
            get {
                return ResourceManager.GetString("VALIDATION_PASSWORD_LENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heslo je u nového účtu povinné.
        /// </summary>
        public static string VALIDATION_REQUIRED_PASSWORD {
            get {
                return ResourceManager.GetString("VALIDATION_REQUIRED_PASSWORD", resourceCulture);
            }
        }
    }
}
