//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VotingWeb.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class VotingAdminRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal VotingAdminRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VotingWeb.Properties.VotingAdminRes", typeof(VotingAdminRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nové hlasování.
        /// </summary>
        public static string BUTTON_CREATE {
            get {
                return ResourceManager.GetString("BUTTON_CREATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zastupitel.
        /// </summary>
        public static string COLUMN_DEPUTY {
            get {
                return ResourceManager.GetString("COLUMN_DEPUTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strana.
        /// </summary>
        public static string COLUMN_PARTY {
            get {
                return ResourceManager.GetString("COLUMN_PARTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hlas.
        /// </summary>
        public static string COLUMN_VOTE {
            get {
                return ResourceManager.GetString("COLUMN_VOTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zastupitel.
        /// </summary>
        public static string DETAIL_DEPUTY {
            get {
                return ResourceManager.GetString("DETAIL_DEPUTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zastupitelský klub.
        /// </summary>
        public static string DETAIL_PARTY {
            get {
                return ResourceManager.GetString("DETAIL_PARTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volba.
        /// </summary>
        public static string DETAIL_VOTE {
            get {
                return ResourceManager.GetString("DETAIL_VOTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Žádný&gt;.
        /// </summary>
        public static string ITEM_NO_PARTY {
            get {
                return ResourceManager.GetString("ITEM_NO_PARTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hlasování.
        /// </summary>
        public static string PAGE_TITLE {
            get {
                return ResourceManager.GetString("PAGE_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nové hlasování.
        /// </summary>
        public static string PAGE_TITLE_CREATE {
            get {
                return ResourceManager.GetString("PAGE_TITLE_CREATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odstranit hlasování.
        /// </summary>
        public static string PAGE_TITLE_DELETE {
            get {
                return ResourceManager.GetString("PAGE_TITLE_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upravit hlasování.
        /// </summary>
        public static string PAGE_TITLE_UPDATE {
            get {
                return ResourceManager.GetString("PAGE_TITLE_UPDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seznam hlasování.
        /// </summary>
        public static string TABLE_TITLE {
            get {
                return ResourceManager.GetString("TABLE_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hlasování vybraného zastupitele k tomuto bodu již existuje.
        /// </summary>
        public static string VALIDATION_VOTING_EXISTS {
            get {
                return ResourceManager.GetString("VALIDATION_VOTING_EXISTS", resourceCulture);
            }
        }
    }
}
