//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VotingWeb.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class VotingRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal VotingRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VotingWeb.Properties.VotingRes", typeof(VotingRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seznam zasedání zastupitelstva.
        /// </summary>
        public static string HEADER_SESSION_LIST {
            get {
                return ResourceManager.GetString("HEADER_SESSION_LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seznam hlasování.
        /// </summary>
        public static string HEADER_TOPIC_LIST {
            get {
                return ResourceManager.GetString("HEADER_TOPIC_LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nezařazení.
        /// </summary>
        public static string PARTY_NONE {
            get {
                return ResourceManager.GetString("PARTY_NONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seznam obcí.
        /// </summary>
        public static string TITLE_HOME {
            get {
                return ResourceManager.GetString("TITLE_HOME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hlasování.
        /// </summary>
        public static string TITLE_VOTING {
            get {
                return ResourceManager.GetString("TITLE_VOTING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Žádný zastupitel.
        /// </summary>
        public static string VOTING_NO_DEPUTY {
            get {
                return ResourceManager.GetString("VOTING_NO_DEPUTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dle strany.
        /// </summary>
        public static string VOTING_TAB_PARTY {
            get {
                return ResourceManager.GetString("VOTING_TAB_PARTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dle volby.
        /// </summary>
        public static string VOTING_TAB_VOTE {
            get {
                return ResourceManager.GetString("VOTING_TAB_VOTE", resourceCulture);
            }
        }
    }
}
