//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VotingData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Email
    {
        public int Id { get; set; }
        public string Subject { get; set; }
        public string Receiver { get; set; }
        public string Body { get; set; }
        public bool IsSent { get; set; }
        public int ErrorCount { get; set; }
        public string ErrorMessage { get; set; }
    }
}
