//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VotingData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Voting
    {
        public int Id { get; set; }
        public int TopicId { get; set; }
        public int DeputyId { get; set; }
        public Nullable<int> PartyId { get; set; }
        public int Vote { get; set; }
    
        public virtual Deputy Deputy { get; set; }
        public virtual Party Party { get; set; }
        public virtual Topic Topic { get; set; }
    }
}
