//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VotingData
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class VotingEntities : DbContext
    {
        public VotingEntities()
            : base("name=VotingEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Deputy> Deputies { get; set; }
        public virtual DbSet<Municipality> Municipalities { get; set; }
        public virtual DbSet<Party> Parties { get; set; }
        public virtual DbSet<Session> Sessions { get; set; }
        public virtual DbSet<Topic> Topics { get; set; }
        public virtual DbSet<Shortcut> Shortcuts { get; set; }
        public virtual DbSet<Email> Emails { get; set; }
        public virtual DbSet<Voting> Votings { get; set; }
    }
}
