//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VotingCommon.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VotingCommon.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrátor.
        /// </summary>
        internal static string ROLE_ADMIN {
            get {
                return ResourceManager.GetString("ROLE_ADMIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editor.
        /// </summary>
        internal static string ROLE_EDITOR {
            get {
                return ResourceManager.GetString("ROLE_EDITOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zdržel/a se.
        /// </summary>
        internal static string VOTE_ABSTAIN {
            get {
                return ResourceManager.GetString("VOTE_ABSTAIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nepřítomný/á.
        /// </summary>
        internal static string VOTE_MISSING {
            get {
                return ResourceManager.GetString("VOTE_MISSING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proti návrhu.
        /// </summary>
        internal static string VOTE_NO {
            get {
                return ResourceManager.GetString("VOTE_NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nevolil/a.
        /// </summary>
        internal static string VOTE_NOT_VOTING {
            get {
                return ResourceManager.GetString("VOTE_NOT_VOTING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pro návrh.
        /// </summary>
        internal static string VOTE_YES {
            get {
                return ResourceManager.GetString("VOTE_YES", resourceCulture);
            }
        }
    }
}
