//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VotingCoreData.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ModelRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ModelRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VotingCoreData.Properties.ModelRes", typeof(ModelRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Popis.
        /// </summary>
        public static string BODY_DESCRIPTION {
            get {
                return ResourceManager.GetString("BODY_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Název.
        /// </summary>
        public static string BODY_NAME {
            get {
                return ResourceManager.GetString("BODY_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jméno.
        /// </summary>
        public static string DEPUTY_FIRSTNAME {
            get {
                return ResourceManager.GetString("DEPUTY_FIRSTNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Příjmení.
        /// </summary>
        public static string DEPUTY_LASTNAME {
            get {
                return ResourceManager.GetString("DEPUTY_LASTNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Klub.
        /// </summary>
        public static string DEPUTY_PARTY {
            get {
                return ResourceManager.GetString("DEPUTY_PARTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tituly za jménem.
        /// </summary>
        public static string DEPUTY_TITLE_POST {
            get {
                return ResourceManager.GetString("DEPUTY_TITLE_POST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tituly před jménem.
        /// </summary>
        public static string DEPUTY_TITLE_PRE {
            get {
                return ResourceManager.GetString("DEPUTY_TITLE_PRE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Popis.
        /// </summary>
        public static string MUNICIPALITY_DESCRIPTION {
            get {
                return ResourceManager.GetString("MUNICIPALITY_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jméno obce.
        /// </summary>
        public static string MUNICIPALITY_NAME {
            get {
                return ResourceManager.GetString("MUNICIPALITY_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Název.
        /// </summary>
        public static string PARTY_NAME {
            get {
                return ResourceManager.GetString("PARTY_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Předsedající.
        /// </summary>
        public static string SESSION_CHAIRMAN {
            get {
                return ResourceManager.GetString("SESSION_CHAIRMAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum konce.
        /// </summary>
        public static string SESSION_DATE_END {
            get {
                return ResourceManager.GetString("SESSION_DATE_END", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum začátku.
        /// </summary>
        public static string SESSION_DATE_START {
            get {
                return ResourceManager.GetString("SESSION_DATE_START", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Název.
        /// </summary>
        public static string SESSION_NAME {
            get {
                return ResourceManager.GetString("SESSION_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Komentář.
        /// </summary>
        public static string TOPIC_COMMENT {
            get {
                return ResourceManager.GetString("TOPIC_COMMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Procedurální.
        /// </summary>
        public static string TOPIC_IS_PROCEDURAL {
            get {
                return ResourceManager.GetString("TOPIC_IS_PROCEDURAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tajné.
        /// </summary>
        public static string TOPIC_IS_SECRET {
            get {
                return ResourceManager.GetString("TOPIC_IS_SECRET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Název.
        /// </summary>
        public static string TOPIC_NAME {
            get {
                return ResourceManager.GetString("TOPIC_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pořadí bodu.
        /// </summary>
        public static string TOPIC_ORDER {
            get {
                return ResourceManager.GetString("TOPIC_ORDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toto pole nemůže zůstat prázdné.
        /// </summary>
        public static string VALIDATION_EMPTY {
            get {
                return ResourceManager.GetString("VALIDATION_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text může být dlouhý nejvýše {1} znaků.
        /// </summary>
        public static string VALIDATION_LENGTH {
            get {
                return ResourceManager.GetString("VALIDATION_LENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zastupitel.
        /// </summary>
        public static string VOTING_DEPUTY {
            get {
                return ResourceManager.GetString("VOTING_DEPUTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zastupitelský klub.
        /// </summary>
        public static string VOTING_PARTY {
            get {
                return ResourceManager.GetString("VOTING_PARTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volba.
        /// </summary>
        public static string VOTING_VOTE {
            get {
                return ResourceManager.GetString("VOTING_VOTE", resourceCulture);
            }
        }
    }
}
